version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
  
    working_directory: ~/manoharglm.github.io
steps:
      - checkout
      
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      
      - run: yarn
   
      - save_cache:
        paths:
          - node_modules
          - ~/.yarn 
          - ~/.cache
        key: v1-dependencies-{{ checksum "package.json" }}
    
      - run: yarn deploy
