version: 1
jobs:
  build:
    working_directory: ~/manoharglm.github.io
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Configure dependencies
          command: |
            git config user.email "manohargunduboina@gmail.com"
            git config user.name "manoharglm"
      - add_ssh_keys:
          fingerprints:
            - "b4:65:ca:53:47:07:8f:76:af:ee:56:b0:0c:da:a3:8f"
      - run:
          name: Deploy build
          command: yarn deploy

      - store_artifacts:
          path: src/images/potrait.jpg
  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
